name: animatediff
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cuda-cccl=12.4.99
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - freetype=2.12.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.3.5.119
  - libcurand-dev=10.3.5.119
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.2.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.10.14
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.28.0
      - aiofiles==23.2.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - appdirs==1.4.4
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.2.0
      - cycler==0.12.1
      - decord==0.6.0
      - diffusers==0.11.1
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - fastapi==0.110.0
      - ffmpy==0.3.2
      - filelock==3.13.3
      - fonttools==4.50.0
      - fsspec==2024.3.1
      - gdown==5.1.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gradio==4.24.0
      - gradio-client==0.14.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - imageio==2.27.0
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - jinja2==3.1.3
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mypy-extensions==1.0.0
      - omegaconf==2.3.0
      - orjson==3.10.0
      - packaging==24.0
      - pandas==2.2.1
      - protobuf==4.25.3
      - psutil==5.9.8
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pyre-extensions==0.0.23
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.34.0
      - regex==2023.12.25
      - rich==13.7.1
      - rpds-py==0.18.0
      - ruff==0.3.4
      - safetensors==0.4.2
      - semantic-version==2.10.0
      - sentry-sdk==1.44.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - starlette==0.36.3
      - tokenizers==0.13.3
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.66.2
      - transformers==4.25.1
      - typer==0.11.1
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uvicorn==0.29.0
      - wandb==0.16.5
      - websockets==11.0.3
      - xformers==0.0.16
      - zipp==3.18.1
